/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CameraMovement, CinematicLook } from './types';

export const CAMERA_MOVEMENTS: CameraMovement[] = [
  {
    id: '1-slow-dolly-in',
    title: 'Slow Dolly In',
    category: 'Dolly/Track',
    description: 'Slow dolly in, camera moves slowly forward toward the subject backdrops.',
    //image: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=800&q=80',
    alt: 'Slow Dolly In',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/1.-Slow-Dolly-In_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/1.-Slow-Dolly-In.mp4',
    promptTemplate: 'Slow dolly in, camera moves slowly forward toward the subject.',
    cinematicTip: 'Perfect for building intimacy and focusing visual tension. Set intensity level of dolly low.',
    intensityLabel: 'Dolly Speed',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 0, z: -35 }
  },
  {
    id: '2-slow-dolly-out',
    title: 'Slow Dolly Out',
    category: 'Dolly/Track',
    description: 'Slow dolly out, camera moves slowly backwards away from the subject.',
    //image: 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?auto=format&fit=crop&w=800&q=80',
    alt: 'Slow Dolly Out',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/2.-Slow-Dolly-Out_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/2.-Slow-Dolly-Out.mp4',
    promptTemplate: 'Slow dolly out, camera moves slowly backwards away from the subject.',
    cinematicTip: 'Reveals the vast context / surrounding environment and isolation of the theme.',
    intensityLabel: 'Pull Speed',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 0, z: 35 }
  },
  {
    id: '3-fast-dolly-in',
    title: 'Fast Dolly In',
    category: 'Dolly/Track',
    description: 'Fast dolly in, camera moves rapidly forward toward the subject background.',
    //image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    alt: 'Fast Dolly In',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/3.-Fast-Dolly-In_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/3.-Fast-Dolly-In.mp4',
    promptTemplate: 'Fast dolly in, camera moves rapidly forward toward the subject, urgent motion.',
    cinematicTip: 'Creates sudden dynamic dramatic impact or cinematic surprise.',
    intensityLabel: 'Push Velocity',
    defaultIntensity: 4,
    motionVector: { x: 0, y: 0, z: -70 }
  },
  {
    id: '4-vertigo-effect-zolly',
    title: 'Vertigo Effect (Zolly)',
    category: 'Zoom/Lens',
    description: 'Dolly zoom vertigo effect: camera dollies back while lens perspective compresses.',
    //image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    alt: 'Vertigo Effect (Zolly)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/4.-Vertigo-Effect-Zolly_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/4.-Vertigo-Effect-Zolly.mp4',
    promptTemplate: 'Vertigo effect, dolly zoom, camera moves backward while zooming in, background expands.',
    cinematicTip: 'Generates intense psychological unease or sudden dizzy realizations.',
    intensityLabel: 'Warp Intensity',
    defaultIntensity: 5,
    motionVector: { x: 0, y: 0, z: -30, rotateX: 5 }
  },
  {
    id: '5-extreme-macro-zoom',
    title: 'Extreme Macro Zoom',
    category: 'Zoom/Lens',
    description: 'Macro precision zoom focused on fine-grain details of structures and surfaces.',
    //image: 'https://images.unsplash.com/photo-1500485035595-cbe6f645feb1?auto=format&fit=crop&w=800&q=80',
    alt: 'Extreme Macro Zoom',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/5-Extreme-Macro-Zoom_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/5-Extreme-Macro-Zoom.mp4',
    promptTemplate: 'Extreme macro zoom, zoom transition from subject to micro details of surface.',
    cinematicTip: 'Ideal for scientific close-up transitions and visual texture exploration.',
    intensityLabel: 'Macro Depth',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: -90 }
  },
  {
    id: '6-cosmic-hyper-zoom',
    title: 'Cosmic Hyper Zoom',
    category: 'Zoom/Lens',
    description: 'Sweeping deep zoom connecting a macro subject with vast space background.',
    //image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=800&q=80',
    alt: 'Cosmic Hyper Zoom',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/6-Cosmic-Hyper-Zoom_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/6-Cosmic-Hyper-Zoom.mp4',
    promptTemplate: 'Cosmic hyper zoom, fast zoom transition from extreme wide view down to macro level.',
    cinematicTip: 'Perfect for infinite seamless macro-to-cosmic cinematic sequences.',
    intensityLabel: 'Zoom speed',
    defaultIntensity: 4,
    motionVector: { x: 0, y: 0, z: -120 }
  },
  {
    id: '7-ots-shot',
    title: 'Over the Shoulder (OTS) Shot',
    category: 'Pan/Tilt',
    description: 'Classic over-the-shoulder framing focusing on dialogue or spatial alignment of subjects.',
    //image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    alt: 'Over the Shoulder (OTS) Shot',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/7.-Over-the-Shoulder-OTS-Shot_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/7.-Over-the-Shoulder-OTS-Shot.mp4',
    promptTemplate: 'Over the shoulder shot, camera mounted behind subject A framing subject B.',
    cinematicTip: 'Standard dialogue layout. Enhances physical connection between subjects.',
    intensityLabel: 'Framing Angle',
    defaultIntensity: 3,
    motionVector: { x: 10, y: 0, z: -10, rotateY: 15 }
  },
  {
    id: '8-fisheye-peephole',
    title: 'Fisheye or Peephole Lens',
    category: 'Zoom/Lens',
    description: 'Dramatic ultra wide-angle glass distortion creating classic circular tunnel view.',
    //image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    alt: 'Fisheye or Peephole Lens',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/8.-Fisheye-or-Peephole-Lens_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/8.-Fisheye-or-Peephole-Lens.mp4',
    promptTemplate: 'Fisheye lens, extreme wide-angle distortion, circular frame.',
    cinematicTip: 'Instantly suggests dynamic spying perspective or immersive security video surveillance feel.',
    intensityLabel: 'Lense Warp',
    defaultIntensity: 4,
    motionVector: { x: 0, y: 0, z: -10, rotateZ: 5 }
  },
  {
    id: '9-reveal-from-behind',
    title: 'Reveal from Behind',
    category: 'Dolly/Track',
    description: 'Laterally tracking reveal emerging outwards from a solid foreground block.',
    //image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80',
    alt: 'Reveal from Behind',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/9.-Reveal-from-Behind-Wipe-Movement_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/9.-Reveal-from-Behind-Wipe-Movement.mp4',
    promptTemplate: 'Wipe movement, camera slides laterally from behind foreground object to reveal the scene.',
    cinematicTip: 'Excellent for establishing visual mystery and geographic transition between layers.',
    intensityLabel: 'Lateral speed',
    defaultIntensity: 3,
    motionVector: { x: -45, y: 0, z: 0 }
  },
  {
    id: '10-through-shot',
    title: 'Through Shot',
    category: 'Drone/Crane',
    description: 'Immersive tracking camera flying perfectly through narrow apertures or open structures.',
    //image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    alt: 'Through Shot',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/10.-Through-Shot-Fly-Through-Aperture_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/10.-Through-Shot-Fly-Through-Aperture.mp4',
    promptTemplate: 'Fly through, camera moves through an opening into the scene.',
    cinematicTip: 'Requires high precision. Beautifully connects exterior atmospheres with indoor settings.',
    intensityLabel: 'Aperture Rate',
    defaultIntensity: 4,
    motionVector: { x: 0, y: 0, z: -60 }
  },
  {
    id: '11-reveal-from-blur',
    title: 'Reveal from Blur',
    category: 'Zoom/Lens',
    description: 'Focus pulls gradually out of soft heavy bokeh into crisp sharpness detail.',
    //image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    alt: 'Reveal from Blur',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/11.-Reveal-from-Blur-Fade-In_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/11.-Reveal-from-Blur-Fade-In.mp4',
    promptTemplate: 'Rack focus, start completely out of focus, slowly pull focus until sharp.',
    cinematicTip: 'Establishes dramatic presence and character awakenings.',
    intensityLabel: 'Pull Speed',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: -5 }
  },
  {
    id: '12-rack-focus',
    title: 'Rack Focus',
    category: 'Zoom/Lens',
    description: 'Focus shifts smoothly from extreme foreground details to background silhouette.',
    //image: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80',
    alt: 'Rack Focus',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/12-Rack-Focus-Foreground-to-Background_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/12-Rack-Focus-Foreground-to-Background.mp4',
    promptTemplate: 'Rack focus, focus shifts from the foreground object to the background subject.',
    cinematicTip: 'Directs viewers attention without shifting physical location.',
    intensityLabel: 'Bokeh shift',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: -8 }
  },
  {
    id: '13-tilt-up',
    title: 'Tilt Up',
    category: 'Pan/Tilt',
    description: 'Smooth vertical panning tilting looking up towards monumental structures.',
    //image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    alt: 'Tilt Up',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/13.-Tilt-Up_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/13.-Tilt-Up.mp4',
    promptTemplate: 'Tilt up, camera pans vertically up from bottom to top.',
    cinematicTip: 'Creates senses of awe and scale when revealing large subjects on screen.',
    intensityLabel: 'Tilt Speed',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 0, z: 10, rotateX: -30 }
  },
  {
    id: '14-tilt-down',
    title: 'Tilt Down',
    category: 'Pan/Tilt',
    description: 'Camera rotates vertically downwards from sky-level toward details or subject on the floor.',
    //image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=80',
    alt: 'Tilt Down',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/14.-Tilt-Down_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/14.-Tilt-Down.mp4',
    promptTemplate: 'Tilt down, camera pans vertically down from top to bottom.',
    cinematicTip: 'Ideal to ground action on specific details while keeping tracking active.',
    intensityLabel: 'Tilt speed',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 0, z: 10, rotateX: 30 }
  },
  {
    id: '15-camera-truck-left',
    title: 'Camera Truck Left',
    category: 'Dolly/Track',
    description: 'Side tracking sliding sideways horizontally tracking character gait.',
    //image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    alt: 'Camera Truck Left',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/15.-Camera-Truck-Left_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/15.-Camera-Truck-Left.mp4',
    promptTemplate: 'Truck left, camera moves sideways on a track to the left.',
    cinematicTip: 'Builds side-scrolling pacing. Stabilize velocity matching walk patterns.',
    intensityLabel: 'Speed Left',
    defaultIntensity: 3,
    motionVector: { x: -45, y: 0, z: 0 }
  },
  {
    id: '16-lateral-truck-right',
    title: 'Lateral Truck Right',
    category: 'Dolly/Track',
    description: 'Dynamic horizontal slide tracking towards the right side on smooth guide rails.',
    //image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    alt: 'Lateral Truck Right',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/16.-Lateral-Truck-Right_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/16.-Lateral-Truck-Right.mp4',
    promptTemplate: 'Truck right, camera moves sideways on a track to the right.',
    cinematicTip: 'Excellent for unveiling vast scenery during fast motion sequences.',
    intensityLabel: 'Speed Right',
    defaultIntensity: 3,
    motionVector: { x: 45, y: 0, z: 0 }
  },
  {
    id: '17-orbit-180',
    title: 'Orbit 180 (Spin)',
    category: 'Pan/Tilt',
    description: 'Sweeping semicircle rotation orbiting subject establishing perspective changes.',
    //image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    alt: 'Orbit 180 (Spin)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/17-Orbit-180_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/17-Orbit-180.mp4',
    promptTemplate: 'Orbit 180, camera moves in a half-circle around the subject.',
    cinematicTip: 'Provides rapid parallax references. Beautiful with multi-layered backdrops.',
    intensityLabel: 'Semicircle speed',
    defaultIntensity: 3,
    motionVector: { x: 35, y: 0, z: -10, rotateY: 30 }
  },
  {
    id: '18-fast-360-orbit',
    title: 'Fast 360 Orbit (Spin)',
    category: 'Pan/Tilt',
    description: 'Highly dynamic full 360 rotation orbiting rapidly around action scenes.',
    //image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
    alt: 'Fast 360 Orbit (Spin)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/18.-Fast-360-Orbit-The-Spin_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/18.-Fast-360-Orbit-The-Spin.mp4',
    promptTemplate: 'Fast 360 orbit, camera spins rapidly 360 degrees around the subject.',
    cinematicTip: 'Imparts cosmic power or extreme pressure, ideal for high drama.',
    intensityLabel: 'Spin speed',
    defaultIntensity: 4,
    motionVector: { x: 50, y: 0, z: -10, rotateY: 90 }
  },
  {
    id: 'true-orbit-180',
    title: 'True Orbit 180 [Seedance 1.5 Pro]',
    category: 'Pan/Tilt',
    description: 'Precision physical semicircle panning, customized for Seedance cinematic models.',
    //image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=80',
    alt: 'True Orbit 180',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/True-Orbit-180-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/True-Orbit-180.mp4',
    promptTemplate: '180 orbit, camera orbits 180 degrees around the [subject].',
    cinematicTip: 'Designed for Seedance model engines with specialized target tokens.',
    intensityLabel: 'Orbit Radius',
    defaultIntensity: 3,
    motionVector: { x: 40, y: 0, z: -15, rotateY: 45 }
  },
  {
    id: 'true-orbit-360',
    title: 'True Orbit 360 [Seedance 1.5 Pro]',
    category: 'Pan/Tilt',
    description: 'Full degree cyclic rotational tracking orbiting subjects smoothly.',
    //image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    alt: 'True Orbit 360',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/True-Orbit-360-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/True-Orbit-360.mp4',
    promptTemplate: 'Fast 360 orbit, camera orbits 360 degrees around the [subject].',
    cinematicTip: 'Seamless looped orbit transitions. Keep coordinates centered.',
    intensityLabel: 'Full Spin Speed',
    defaultIntensity: 4,
    motionVector: { x: 60, y: 0, z: -10, rotateY: 90 }
  },
  {
    id: '19-slow-cinematic-arc',
    title: 'Slow Cinematic Arc',
    category: 'Pan/Tilt',
    description: 'An elegant long curved cinematic sweep panning around side profiles slowly.',
    //image: 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?auto=format&fit=crop&w=800&q=80',
    alt: 'Slow Cinematic Arc',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/19.-Slow-Cinematic-Arc_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/19.-Slow-Cinematic-Arc.mp4',
    promptTemplate: 'Slow cinematic arc, camera moves in a wide curve to reveal side profile.',
    cinematicTip: 'Lends monumental status to actors before they initiate action.',
    intensityLabel: 'Arc Speed',
    defaultIntensity: 2,
    motionVector: { x: 25, y: 5, z: -20, rotateY: 25 }
  },
  {
    id: '20-pedestal-down',
    title: 'Pedestal Down',
    category: 'Dolly/Track',
    description: 'The physical crane arm lowers the camera vertically down smoothly.',
    //image: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80',
    alt: 'Pedestal Down',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/20-Pedestal-Down_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/20-Pedestal-Down.mp4',
    promptTemplate: 'Pedestal down, camera lowers vertically straight down.',
    cinematicTip: 'Maintains flat level perspective unlike a vertical camera tilt.',
    intensityLabel: 'Lift Rate',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 35, z: 0 }
  },
  {
    id: '21-pedestal-up',
    title: 'Pedestal Up',
    category: 'Dolly/Track',
    description: 'Camera rig climbs vertically straight up, panning zero perspective warp.',
    //image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    alt: 'Pedestal Up',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/21.-Pedestal-Up_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/21.-Pedestal-Up.mp4',
    promptTemplate: 'Pedestal up, camera rises vertically straight up from waist to eye level.',
    cinematicTip: 'Lifts focus slowly revealing landscape details over dynamic thresholds.',
    intensityLabel: 'Rise Rate',
    defaultIntensity: 2,
    motionVector: { x: 0, y: -35, z: 0 }
  },
  {
    id: '22-crane-up',
    title: 'Crane Up (High Angle Reveal)',
    category: 'Drone/Crane',
    description: 'Soaring high angle reveal ascending rapidly straight up looking down.',
    //image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=800&q=80',
    alt: 'Crane Up (High Angle Reveal)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/22.-Crane-Up-High-Angle-Reveal_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/22.-Crane-Up-High-Angle-Reveal.mp4',
    promptTemplate: 'Crane up, camera lifts high into the air.',
    cinematicTip: 'Expands spatial visibility, providing a classic movie opening feel.',
    intensityLabel: 'Air lift speed',
    defaultIntensity: 3,
    motionVector: { x: 0, y: -50, z: -20, rotateX: -15 }
  },
  {
    id: '23-crane-down',
    title: 'Crane Down (Landing)',
    category: 'Drone/Crane',
    description: 'Gracefully descending camera glide ending at ground level close-ups.',
    //image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    alt: 'Crane Down (Landing)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/23.-Crane-Down-Landing_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/23.-Crane-Down-Landing.mp4',
    promptTemplate: 'Crane down, camera descends slowly to the subject.',
    cinematicTip: 'Connects atmospheric landscape views down into character-centric focus.',
    intensityLabel: 'Drop speed',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 50, z: 20, rotateX: 15 }
  },
  {
    id: '24-smooth-optical-zoom-in',
    title: 'Smooth Optical Zoom In',
    category: 'Zoom/Lens',
    description: 'Lens magnifying perspective dynamically while camera rig stays stationary.',
    //image: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=800&q=80',
    alt: 'Smooth Optical Zoom In',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/24.-Smooth-Optical-Zoom-In_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/24.-Smooth-Optical-Zoom-In.mp4',
    promptTemplate: 'Smooth optical zoom in, lens magnifies subject, camera stays stationary.',
    cinematicTip: 'Ensures zero physical shift of background distortion, mimicking studio telephotos.',
    intensityLabel: 'Zoom Magnitude',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: -55 }
  },
  {
    id: '25-smooth-optical-zoom-out',
    title: 'Smooth Optical Zoom Out',
    category: 'Zoom/Lens',
    description: 'Lens focal length broadens out, introducing wide cinematic borders.',
    //image: 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?auto=format&fit=crop&w=800&q=80',
    alt: 'Smooth Optical Zoom Out',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/25.-Smooth-Optical-Zoom-Out_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/25.-Smooth-Optical-Zoom-Out.mp4',
    promptTemplate: 'Smooth optical zoom out, lens widens, background becomes blurry.',
    cinematicTip: 'Isolates and grounds the primary focus while expanding horizontal layouts.',
    intensityLabel: 'Wide Expansion',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: 55 }
  },
  {
    id: '26-snap-zoom',
    title: 'Snap Zoom (Crash Zoom)',
    category: 'Zoom/Lens',
    description: 'Violent and rapid focus snap pulling instantly directly into characters.',
    //image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    alt: 'Snap Zoom (Crash Zoom)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/26-Snap-Zoom-Crash-Zoom_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/26-Snap-Zoom-Crash-Zoom.mp4',
    promptTemplate: 'Snap zoom, crash zoom, rapid zoom directly into the eyes.',
    cinematicTip: 'Perfect for comedic timing, retro action reveals, or sudden dread.',
    intensityLabel: 'Focus Velocity',
    defaultIntensity: 5,
    motionVector: { x: 0, y: 0, z: -110 }
  },
  {
    id: '27-drone-fly-over',
    title: 'Drone Fly Over',
    category: 'Drone/Crane',
    description: 'High altitude survey glide tracking directly forward over landscapes.',
    //image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    alt: 'Drone Fly Over',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/27.-Drone-Fly-Over_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/27.-Drone-Fly-Over.mp4',
    promptTemplate: 'Drone fly over, high altitude flight moving forward over the landscape.',
    cinematicTip: 'Ideal to outline majestic settings and geographic spatial size.',
    intensityLabel: 'Altitude Speed',
    defaultIntensity: 3,
    motionVector: { x: 0, y: -10, z: -60 }
  },
  {
    id: '28-epic-drone-reveal',
    title: 'Epic Drone Reveal',
    category: 'Drone/Crane',
    description: 'Sweeping rising flight tilting downwards generating grand reveal structures.',
    //image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=800&q=80',
    alt: 'Epic Drone Reveal',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/28.-Epic-Drone-Reveal_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/28.-Epic-Drone-Reveal.mp4',
    promptTemplate: 'Epic drone reveal, rising and tilting down to reveal the scene.',
    cinematicTip: 'Great for transitions introducing wide urban architecture setups.',
    intensityLabel: 'Ascending Lift',
    defaultIntensity: 4,
    motionVector: { x: 0, y: -45, z: -30, rotateX: -20 }
  },
  {
    id: '29-large-scale-drone-orbit',
    title: 'Large Scale Drone Orbit',
    category: 'Drone/Crane',
    description: 'Massive soaring 360 rotation orbiting majestic topological views.',
    //image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    alt: 'Large Scale Drone Orbit',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/29.-Large-Scale-Drone-Orbit_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/29.-Large-Scale-Drone-Orbit.mp4',
    promptTemplate: 'Large scale drone orbit, massive sweeping circle around the landscape.',
    cinematicTip: 'Enhances landscape depth and three-dimensional parallax mapping.',
    intensityLabel: 'Orbit Circle Radius',
    defaultIntensity: 3,
    motionVector: { x: 65, y: -20, z: -15, rotateY: 60 }
  },
  {
    id: '30-top-down-gods-eye',
    title: 'Top Down (God\'s Eye View)',
    category: 'Drone/Crane',
    description: 'Perfect vertical top-down camera mapping directly perpendicular to ground.',
    //image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    alt: 'Top Down (God\'s Eye View)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/30.-Top-Down-Gods-Eye-View_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/30.-Top-Down-Gods-Eye-View.mp4',
    promptTemplate: 'Top down shot, camera pointing straight down, slow twist.',
    cinematicTip: 'Unfolds layout geometry beautifully. Add subtle camera roll.',
    intensityLabel: 'Twist Intensity',
    defaultIntensity: 2,
    motionVector: { x: 0, y: 0, z: 10, rotateX: 90, rotateZ: 15 }
  },
  {
    id: '31-fpv-drone-dive',
    title: 'FPV Drone Aggressive (Drone Dive)',
    category: 'Drone/Crane',
    description: 'High intensity rapid descend spiral diving down colossal vertical blocks.',
    //image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    alt: 'FPV Drone Aggressive (Drone Dive)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/31.-FPV-Drone-Aggressive-Drone-Dive_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/31.-FPV-Drone-Aggressive-Drone-Dive.mp4',
    promptTemplate: 'FPV drone dive, aggressive diving motion down a vertical structure.',
    cinematicTip: 'Highly cinematic action sequences. Best paired with high intensity.',
    intensityLabel: 'Dive Gravity',
    defaultIntensity: 5,
    motionVector: { x: 0, y: 80, z: -50, rotateX: 45, rotateZ: 25 }
  },
  {
    id: '32-handheld-documentary',
    title: 'Handheld Documentary Style',
    category: 'Pan/Tilt',
    description: 'Classic raw shaky camera movement suggesting photoreal documentary context.',
    //image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    alt: 'Handheld Documentary Style',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/32.-Handheld-Documentary-Style_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/32.-Handheld-Documentary-Style.mp4',
    promptTemplate: 'Handheld camera, shaky motion, natural movement, documentary style.',
    cinematicTip: 'Adds extreme sense of realism and situational gravity to action.',
    intensityLabel: 'Shake Intensity',
    defaultIntensity: 3,
    motionVector: { x: 5, y: -5, z: 2, rotateX: 3, rotateY: -3, rotateZ: 2 }
  },
  {
    id: '33-whip-pan',
    title: 'Whip Pan',
    category: 'Pan/Tilt',
    description: 'Ultra fast lateral panning generating seamless blur motion paths.',
    //image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=80',
    alt: 'Whip Pan',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/33-Whip-Pan_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/33-Whip-Pan.mp4',
    promptTemplate: 'Whip pan, camera whips violently to the side with extreme directional motion blur.',
    cinematicTip: 'Ideal to link sudden spatial viewpoints together and keep action dynamic.',
    intensityLabel: 'Blur Speed',
    defaultIntensity: 5,
    motionVector: { x: 80, y: 0, z: 0, rotateY: 90 }
  },
  {
    id: '34-dutch-angle-roll',
    title: 'Dutch Angle (Roll)',
    category: 'Pan/Tilt',
    description: 'Camera orientation rotates off-axis on the Z plane, suggesting psychological distortion.',
    //image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    alt: 'Dutch Angle (Roll)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/34.-Dutch-Angle-Roll_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/34.-Dutch-Angle-Roll.mp4',
    promptTemplate: 'Dutch angle, camera roll, tilted sideways on Z-axis.',
    cinematicTip: 'Grounded in noir tension or critical panic events.',
    intensityLabel: 'Z Tilt Angle',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: 0, rotateZ: 25 }
  },
  {
    id: '35-leading-shot',
    title: 'Leading Shot (Backward Tracking)',
    category: 'Dolly/Track',
    description: 'Camera steps backward keeping subject static while capturing gait forward.',
    //image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80',
    alt: 'Leading Shot (Backward Tracking)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/35.-Leading-Shot-Backward-Tracking.mp4_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/35.-Leading-Shot-Backward-Tracking.mp4',
    promptTemplate: 'Leading shot, camera moves backward matching the subject\'s speed.',
    cinematicTip: 'Anchors face tracking smoothly, building anticipation of what is ahead.',
    intensityLabel: 'Tracking Rate',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: 45 }
  },
  {
    id: '36-following-shot',
    title: 'Following Shot (Forward Tracking)',
    category: 'Dolly/Track',
    description: 'Direct step-forward following shot tracking subjects from behind.',
    //image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    alt: 'Following Shot (Forward Tracking)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/36.-Following-Shot-Forward-Tracking.mp4_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/36.-Following-Shot-Forward-Tracking.mp4',
    promptTemplate: 'Following shot, camera follows behind the subject matching speed.',
    cinematicTip: 'Allows the audience to explore characters viewpoints incrementally.',
    intensityLabel: 'Follow Speed',
    defaultIntensity: 3,
    motionVector: { x: 0, y: 0, z: -45 }
  },
  {
    id: '37-side-tracking',
    title: 'Side Tracking (Parallel)',
    category: 'Dolly/Track',
    description: 'Lateral side-view tracking aligning profile posture directly centered.',
    //image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    alt: 'Side Tracking (Parallel)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/37.-Side-Tracking-Parallel_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/37.-Side-Tracking-Parallel.mp4',
    promptTemplate: 'Side tracking, camera trucks alongside the subject.',
    cinematicTip: 'Gives elegant rhythmic momentum to side-scrolling pacing.',
    intensityLabel: 'Parallel Speed',
    defaultIntensity: 3,
    motionVector: { x: 45, y: 0, z: 0 }
  },
  {
    id: '38-pov-walk',
    title: 'POV Walk (First Person Walk)',
    category: 'Dolly/Track',
    description: 'Walking layout view reproducing authentic height-aligned human strides.',
    //image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
    alt: 'POV Walk (First Person Walk)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/38.-POV-Walk-First-Person-Walk_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/38.-POV-Walk-First-Person-Walk.mp4',
    promptTemplate: 'POV walk, first person camera moving forward with bobbing motion.',
    cinematicTip: 'Maximizes viewer perspective immersion within horror of survival topics.',
    intensityLabel: 'Stride Pace',
    defaultIntensity: 3,
    motionVector: { x: 0, y: -2, z: -35, rotateZ: 1 }
  },
  {
    id: '39-hyperlapse',
    title: 'Hyperlapse (Moving Time-Lapse)',
    category: 'Dolly/Track',
    description: 'Rapid spatial translation condensed into beautiful accelerated sequences.',
    //image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=800&q=80',
    alt: 'Hyperlapse (Moving Time-Lapse)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/39.-Hyperlapse-Moving-Time-Lapse_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/39.-Hyperlapse-Moving-Time-Lapse.mp4',
    promptTemplate: 'Hyperlapse, camera moves forward rapidly, time accelerated, fast motion, light trails.',
    cinematicTip: 'Perfect to illustrate rapid transitions, busy schedule, or city sunset loops.',
    intensityLabel: 'Time Warping Factor',
    defaultIntensity: 4,
    motionVector: { x: 0, y: 0, z: -80 }
  },
  {
    id: '40-barrel-roll',
    title: 'Barrel Roll (Vortex Inception Shot)',
    category: 'Pan/Tilt',
    description: 'Dizzying clockwise barrel rotation pulling perspective into vortex loops.',
    //image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=80',
    alt: 'Barrel Roll (Vortex Inception)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/40.-Barrel-Roll-Vortex-Inception-Shot_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/40.-Barrel-Roll-Vortex-Inception-Shot.mp4',
    promptTemplate: 'Barrel roll, camera spins 360 degrees clockwise while moving forward, disorienting.',
    cinematicTip: 'Creates immense psychological stress, mimicking fighter jet maneuvers.',
    intensityLabel: 'Vortex Speed',
    defaultIntensity: 4,
    motionVector: { x: 0, y: 0, z: -30, rotateZ: 90 }
  },
  {
    id: '41-bullet-time',
    title: 'Bullet Time (Frozen Moment)',
    category: 'Pan/Tilt',
    description: 'Immersive temporal freeze with camera orbital pan tracking static actions.',
    //image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    alt: 'Bullet Time (Frozen Moment)',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/41.-Bullet-Time-Frozen-Moment_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/41.-Bullet-Time-Frozen-Moment.mp4',
    promptTemplate: 'Bullet time, frozen moment, ultra slow motion, camera orbit right.',
    cinematicTip: 'Immortalizes peak gravity-defying moments in combat or stunt displays.',
    intensityLabel: 'Temporal Resolution',
    defaultIntensity: 5,
    motionVector: { x: 45, y: 0, z: -5, rotateY: 35 }
  },
  {
    id: '42-worms-eye',
    title: 'Worm’s Eye Tracking (Ground Level)',
    category: 'Dolly/Track',
    description: 'Lowest point ground view tracking forward looking directly upwards.',
    //image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    alt: 'Worm’s Eye Tracking',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/42.-Worms-Eye-Tracking-Ground-Level_preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/42.-Worms-Eye-Tracking-Ground-Level.mp4',
    promptTemplate: 'Worm\'s eye view, low angle tracking, camera moves along the ground looking up.',
    cinematicTip: 'Perfect to trace shoe footsteps, sports matches, or dynamic small creatures.',
    intensityLabel: 'Angle low pitch',
    defaultIntensity: 3,
    motionVector: { x: 0, y: -45, z: -40, rotateX: 30 }
  }
];

export const CINEMATIC_LOOKS: CinematicLook[] = [
  {
    id: 'look-high-key',
    title: 'High Key',
    category: 'Lighting',
    description: 'High key lighting, bright and airy, low contrast, clean white tones, commercial aesthetic',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/18.-High-Key-Bright-Airy-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/18.-High-Key-Bright-Airy.mp4'
  },
  {
    id: 'look-solarpunk',
    title: 'Solarpunk',
    category: 'Cinema Legends',
    description: 'Solarpunk aesthetic, eco-futurism, lush greenery, bright sunlight, white and green palette',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/8.-Solarpunk-Eco-Utopia-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/8.-Solarpunk-Eco-Utopia.mp4'
  },
  {
    id: 'look-golden-hour',
    title: 'Golden Hour',
    category: 'Lighting',
    description: 'Golden Hour lighting, sun-drenched, warm orange haze, backlit tree, long shadows, cinematic landscape',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/14.-Golden-Hour-Warmth-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/14.-Golden-Hour-Warmth.mp4'
  },
  {
    id: 'look-steampunk',
    title: 'Steampunk',
    category: 'Cinema Legends',
    description: 'Steampunk aesthetic, brass and copper, Victorian industrial, warm golden atmosphere, steam',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/9.-Steampunk-Victorian-Industrial-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/9.-Steampunk-Victorian-Industrial.mp4'
  },
  {
    id: 'look-kodachrome',
    title: 'Kodachrome',
    category: 'Film Stocks',
    description: 'Kodachrome film, vintage photography, warm tones, archival footage, analog look',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/11.-Kodachrome-Nostalgia-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/11.-Kodachrome-Nostalgia.mp4'
  },
  {
    id: 'look-candlelight',
    title: 'Candlelight',
    category: 'Lighting',
    description: 'Candlelight, fire lighting, warm glow, deep shadows, intimate atmosphere, chiaroscuro',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/19.-Candlelight-Baroque-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/19.-Candlelight-Baroque.mp4'
  },
  {
    id: 'look-wes-anderson',
    title: 'Wes Anderson',
    category: 'Cinema Legends',
    description: 'Pastel color palette, Wes Anderson style, 35mm film look, flat lighting, symmetrical composition',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/7.-Wes-Anderson-Pastel-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/7.-Wes-Anderson-Pastel.mp4'
  },
  {
    id: 'look-sepia',
    title: 'Sepia',
    category: 'Film Stocks',
    description: 'Sepia color grading, monochromatic brown tint, Western movie aesthetic, warm atmosphere',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/13.-Sepia-Old-West-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/13.-Sepia-Old-West.mp4'
  },
  {
    id: 'look-bleach-bypass',
    title: 'Bleach Bypass',
    category: 'Cinema Legends',
    description: 'Bleach bypass, silver retention, desaturated, high contrast, gritty texture',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/2.-Bleach-Bypass-Grit-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/2.-Bleach-Bypass-Grit.mp4'
  },
  {
    id: 'look-nordic-noir',
    title: 'Nordic Noir',
    category: 'Cinema Legends',
    description: 'Nordic noir aesthetic, desaturated blue and grey, overcast lighting, bleak atmosphere, muted tones',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/5.-Nordic-Noir-Cold-Drama-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/5.-Nordic-Noir-Cold-Drama.mp4'
  },
  {
    id: 'look-film-noir',
    title: 'Film Noir',
    category: 'Cinema Legends',
    description: 'Film Noir, black and white, chiaroscuro, high contrast monochrome, dramatic shadows',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/4.-Film-Noir-Chiaroscuro-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/4.-Film-Noir-Chiaroscuro.mp4'
  },
  {
    id: 'look-silhouette',
    title: 'Silhouette',
    category: 'Lighting',
    description: 'Silhouette style, backlit subject, high contrast, pitch black foreground',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/20.-Silhouette-Graphic-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/20.-Silhouette-Graphic.mp4'
  },
  {
    id: 'look-teal-orange',
    title: 'Teal & Orange',
    category: 'Cinema Legends',
    description: 'Teal and orange color grading, blockbuster aesthetic, complementary colors, cyan and orange',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/1.-Teal-Orange-Blockbuster-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/1.-Teal-Orange-Blockbuster.mp4'
  },
  {
    id: 'look-cinestill-800t',
    title: 'CineStill 800T',
    category: 'Film Stocks',
    description: 'CineStill 800T, red halation, tungsten balance, cinematic night, 35mm film',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/12.-CineStill-800T-Night-Glow-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/12.-CineStill-800T-Night-Glow.mp4'
  },
  {
    id: 'look-blue-hour',
    title: 'Blue Hour',
    category: 'Lighting',
    description: 'Blue hour, twilight, cold tones, deep blue, melancholic lighting',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/15.-Blue-Hour-Cold-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/15.-Blue-Hour-Cold.mp4'
  },
  {
    id: 'look-bioluminescence',
    title: 'Bioluminescence',
    category: 'Lighting',
    description: 'Bioluminescence, glowing plants, deep blue night, magical atmosphere, organic neon',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/21.-Bioluminescence-Fantasy-Night-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/21.-Bioluminescence-Fantasy-Night.mp4'
  },
  {
    id: 'look-matrix-green',
    title: 'Matrix Green',
    category: 'Cinema Legends',
    description: 'Green tint, fluorescent green, Matrix aesthetic, dystopian color palette',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/6.-Matrix-Green-Fluorescent-Dystopia-2-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/6.-Matrix-Green-Fluorescent-Dystopia-2.mp4'
  },
  {
    id: 'look-night-vision',
    title: 'Night Vision',
    category: 'Film Stocks',
    description: 'CCTV footage, night vision, monochromatic green, security camera, grainy, surveillance feed',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/10.-Night-Vision-CCTV-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/10.-Night-Vision-CCTV.mp4'
  },
  {
    id: 'look-technicolor',
    title: 'Technicolor',
    category: 'Cinema Legends',
    description: 'Technicolor, 3-strip color, hyper-saturated, vintage cinema, vibrant colors',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/3.-Technicolor-Vintage-Vibrant-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/3.-Technicolor-Vintage-Vibrant.mp4'
  },
  {
    id: 'look-duotone',
    title: 'Duotone',
    category: 'Stylized & Abstract',
    description: 'Duotone, double color exposure, [Color A] and [Color B] palette, pop art',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/23.-Duotone-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/23.-Duotone.mp4'
  },
  {
    id: 'look-cyberpunk',
    title: 'Cyberpunk',
    category: 'Lighting',
    description: 'Cyberpunk, neon lighting, magenta and cyan, reflective visor, neon noir, wet texture',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/16.-Cyberpunk-Neon-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/16.-Cyberpunk-Neon.mp4'
  },
  {
    id: 'look-ultraviolet',
    title: 'Ultraviolet',
    category: 'Stylized & Abstract',
    description: 'Ultraviolet light, blacklight, fluorescent glow, UV reactive, deep purple',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/27.-Ultraviolet-Blacklight-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/27.-Ultraviolet-Blacklight.mp4'
  },
  {
    id: 'look-infrared',
    title: 'Infrared',
    category: 'Stylized & Abstract',
    description: 'Infrared photography, Kodak Aerochrome, pink trees, surreal colors, false color',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/22.-Infrared-Aerochrome-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/22.-Infrared-Aerochrome.mp4'
  },
  {
    id: 'look-thermal-imaging',
    title: 'Thermal Imaging',
    category: 'Stylized & Abstract',
    description: 'Thermal imaging, heat map, infrared camera, predator vision',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/26.-Thermal-Imaging-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/26.-Thermal-Imaging.mp4'
  },
  {
    id: 'look-sodium-vapor',
    title: 'Sodium Vapor',
    category: 'Lighting',
    description: 'Sodium vapor lighting, orange streetlights, urban night, industrial atmosphere',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/17.-Sodium-Vapor-Industrial-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/17.-Sodium-Vapor-Industrial.mp4'
  },
  {
    id: 'look-cross-processed',
    title: 'Cross-Processed',
    category: 'Stylized & Abstract',
    description: 'Cross-processed, color shift, unnatural colors, lomo style, chemical imbalance',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/25.-Cross-Processed-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/25.-Cross-Processed.mp4'
  },
  {
    id: 'look-selective-color',
    title: 'Selective Color',
    category: 'Stylized & Abstract',
    description: 'Selective color, monochrome with red splash, Sin City style, color isolation',
    video: 'https://aishotstudio.com/wp-content/uploads/2026/01/24.-Selective-Color-Sin-City-preview.mp4',
    videoFull: 'https://aishotstudio.com/wp-content/uploads/2026/01/24.-Selective-Color-Sin-City.mp4'
  }
];
